### ISSUE TITLE
ABORDAGEM DE DESENVOLVIMENTO DE SOFTWARE

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Meio-a-Meio#17]
**Decrição**
o planejamento do projeto e a abordagem informada **estão em desacordo**.

**Comment by libruna** [comment]
@marsicanogeorge Pode especificar um pouco mais essa issue ?

**Comment by marsicanogeorge** [comment]
o planejamento do projeto está cascata e a abordagem fala em ágil. Não faz sentido. Se a abordagem é ágil o planejamento deve seguir a mesma estratégia.
