### ISSUE TITLE
Canvas - Entregas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Meio-a-Meio#24]
**Descrição**
os resultados precisam ser verificáveis e objetivos. Os resultados, abaixo, não são nada verificáveis e objetivos.

![image](https://user-images.githubusercontent.com/68402547/180839343-d460475f-ed0e-4452-a15c-4f5d192a1025.png)

**Comment by ciro-c** [comment]
Resolvido
