### ISSUE TITLE
Canvas - MVP

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Meio-a-Meio#25]
**Descrição**
O MVP deve conter as funcionalidades essenciais ao funcionamento do produto e de alto valor de negócio. O MVP estabelecido pela equipe para por controle de ponto, matrícula, registro de inadimplência... mas, não trata, por exemplo, da criação das turmas, dos cursos. Isso não é essencial para um produto voltado a gestão escolar?

![image](https://user-images.githubusercontent.com/68402547/180839657-1d07b4b7-5bd6-4f1a-bdc7-54c2cf04390a.png)

**Comment by ciro-c** [comment]
Feito
