### ISSUE TITLE
Cadastrar aluno (FGM2)

### ISSUE THREAD

**Issue by ciro-c** [mdsreq-fga-unb/2022.1-Meio-a-Meio#39]
## Descrição

O administrador deve ser capaz cadastrar informações dos alunos.

Dados obrigatórios para cadastro:
- Nome completo;
- Data de nascimento;
- Sexo;
- Nacionalidade;
- CPF;
- RG/UF ou RNE/UF;
- Órgão emissor;
- Celular com DDD;
- CRM/UF
- Formação acadêmica;
- Especialização;
- Status do financeiro (inadimplência);
- Endereço (CEP, número, complemento, bairro, cidade, estado, endereco_residencial).

Dados não-obrigatórios:
 - Telefone residencial com DDD;
 - Observações.

## Tarefas

- [x] Criar endpoint alunos;
- [x] Fazer validações de informações.

## Critério de aceitação

- [x] Matrícula ser gerada automaticamente;
- [x] Não poder cadastrar aluno se o CPF e CRM/UF já estiverem cadastrados;
- [x] Conseguir registrar no banco de dados.

**Comment by libruna** [comment]
Cadastro de aluno implementado.
