### ISSUE TITLE
Cadastrar professores (FGM4)

### ISSUE THREAD

**Issue by ciro-c** [mdsreq-fga-unb/2022.1-Meio-a-Meio#40]
## Descrição

O administrador deve ser capaz de cadastrar informações dos professores.

Dados obrigatórios:
 - Nome completo;
 - Data de nascimento;
 - Nacionalidade;
 - Sexo;
 - Email;
 - Celular com DDD;
 - CPF;
 - RG/UF ou RNE/UF;
 - Órgão emissor;
 - CRM/UF;
 - Formação acadêmica;
 - Especialização;
 - Especialista.

Dados não-obrigatórios:
 -  Observações.

## Tarefas

- [x] Criar endpoint professores;
- [x] Fazer validações de informações.

## Critério de aceitação

- [x] Não cadastrar se já existir um aluno cadastrado com a mesma matrícula, se não for inserida, gerar matrícula automaticamente;
- [x] Não poder cadastrar professor se o CPF e CRM/UF já estiverem cadastrado;
- [x] Se o professor não for especialista, não deve ser obrigatório inserir o CRM/UF;
- [x] Conseguir registrar no banco de dados.

**Comment by libruna** [comment]
Cadastro de professor implementado.

**Comment by libruna** [comment]
Issue reaberta, os dados sofreram alterações

**Comment by libruna** [comment]
Issue reaberta, os dados sofreram alterações
