### ISSUE TITLE
Cadastrar disciplina (FGM6)

### ISSUE THREAD

**Issue by ciro-c** [mdsreq-fga-unb/2022.1-Meio-a-Meio#41]
## Descrição

O administrador deve ser capaz de cadastrar disciplinas.
Dados obrigatórios:
- nome
- carga horaria
- nota
- professor

## Tarefas

- [x] Criar endpoint disciplinas
- [x] Fazer validações de informações

## Critério de aceitação

- [x] Não poder cadastrar disciplina se o nome e a carga horaria ja esteja cadastrado
- [x] Conseguir registrar no banco de dados

**Comment by libruna** [comment]
Cadastro de disciplina implementado.
