### ISSUE TITLE
Cadastrar curso (FGM5)

### ISSUE THREAD

**Issue by ciro-c** [mdsreq-fga-unb/2022.1-Meio-a-Meio#48]
## Descrição

O administrador deve ser capaz de cadastrar cursos.

Dados obrigatórios:
- nome

Dados não-obrigatórios:
- Unidade

## Tarefas

- [x] Criar endpoint cursos

## Critério de aceitação

- [x] Não poder cadastrar curso se o nome e a unidade já estiverem cadastrados;
- [x] Conseguir registrar no banco de dados.

**Comment by libruna** [comment]
Cadastro de curso implementado.
