### ISSUE TITLE
cadastrar aluno (FGM2)

### ISSUE THREAD

**Issue by Nicolas-Roberto** [mdsreq-fga-unb/2022.1-Meio-a-Meio#71]
## Descrição

O administrador deve ser capaz cadastrar informações dos alunos (matricula, idade….).

## Tarefas

- [x] Tela para informar dados do aluno
- [x]  Conexão com o back-end

## Critério de aceitação

- [x] Não permitir cadastrar pessoas já cadastradas no sistema

**Comment by libruna** [comment]
Issue repetida
