### ISSUE TITLE
cadastrar professor (FGM4)

### ISSUE THREAD

**Issue by Nicolas-Roberto** [mdsreq-fga-unb/2022.1-Meio-a-Meio#72]
## Descrição

O administrador deve ser capaz de cadastrar informações dos professores.

## Tarefas

- [x] Tela para informar dados do professor
- [x] Endpoint ser adicionado dentro da rota /professores

## Critério de aceitação

- [x] Não deve ser possível cadastrar o mesmo professor mais de uma vez

**Comment by libruna** [comment]
Issue repetida
