### ISSUE TITLE
cadastrar turma (FGM9)

### ISSUE THREAD

**Issue by Nicolas-Roberto** [mdsreq-fga-unb/2022.1-Meio-a-Meio#74]
## Descrição

O administrador deve ser capaz de criar turmas das disciplinas.

## Tarefas

- [x] Tela para informar dados do aluno
- [x]  Endpoint ser adicionado dentro da rota /turmas

## Critério de aceitação

- [x] Não deve ser possível cadastrar uma turma existente

**Comment by libruna** [comment]
Issue repetida
