### ISSUE TITLE
registrar lista de presença (FP19)

### ISSUE THREAD

**Issue by Nicolas-Roberto** [mdsreq-fga-unb/2022.1-Meio-a-Meio#78]
## Descrição

O professor deve ser capaz de cadastrar a lista de presença.

## Tarefas

- [x] Tela para informar dados da lista de presença
- [x]  Endpoint ser adicionado dentro da rota /professor

## Critério de aceitação

- [x] Somente o professor cadastrar a lista de presença

**Comment by samuel-sato** [comment]
atividades ou lista de presença?

**Comment by Nicolas-Roberto** [comment]
Era pra ser lista, isso ta pronto?
Pq se não a gente pode alterar algumas coisas
