### ISSUE TITLE
matricular aluno em curso (FGM30)

### ISSUE THREAD

**Issue by Nicolas-Roberto** [mdsreq-fga-unb/2022.1-Meio-a-Meio#80]
## Descrição

O administrador deve ser capaz de matricular aluno em curso.

## Tarefas

- [x] Tela para informar  aluno e curso
- [x]  Endpoint ser adicionado dentro da rota /adm

## Critério de aceitação

- [x] O aluno não deve estar matriculado no curso

**Comment by libruna** [comment]
Issue repetida
